name: stem-sep
channels:
  - apple
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ffmpeg
  - libsndfile
  - pip
  - pip:
    - fastapi==0.115.0
    - uvicorn[standard]==0.32.0
    - python-multipart==0.0.12
    - pydantic==2.9.2
    - pydantic-settings==2.5.2
    - python-json-logger==2.0.7
    - aiofiles==24.1.0

